import 'package:flutter/material.dart';
import 'package:flutterapp/woxisapp/generatedantrenmandetaylar2widget/generated/Generated35KgWidget1.dart';
import 'package:flutterapp/woxisapp/generatedantrenmandetaylar2widget/generated/GeneratedVector3Widget2.dart';
import 'package:flutterapp/woxisapp/generatedantrenmandetaylar2widget/generated/GeneratedTekrarSaysWidget1.dart';
import 'package:flutterapp/woxisapp/generatedantrenmandetaylar2widget/generated/Generated8Widget1.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/woxisapp/generatedantrenmandetaylar2widget/generated/GeneratedVector2Widget2.dart';
import 'package:flutterapp/woxisapp/generatedantrenmandetaylar2widget/generated/GeneratedPageHeaderWidget6.dart';
import 'package:flutterapp/woxisapp/generatedantrenmandetaylar2widget/generated/GeneratedButtonPrimaryWidget7.dart';
import 'package:flutterapp/woxisapp/generatedantrenmandetaylar2widget/generated/GeneratedalmaArlWidget1.dart';
import 'package:flutterapp/woxisapp/generatedantrenmandetaylar2widget/generated/GeneratedWOXIS_SIYAH1Widget5.dart';
import 'package:flutterapp/woxisapp/generatedantrenmandetaylar2widget/generated/GeneratedGroup13Widget1.dart';
import 'package:flutterapp/woxisapp/generatedantrenmandetaylar2widget/generated/GeneratedIOSStatusBarBlackWidget6.dart';
import 'package:flutterapp/woxisapp/generatedantrenmandetaylar2widget/generated/GeneratedVector1Widget2.dart';
import 'package:flutterapp/woxisapp/generatedantrenmandetaylar2widget/generated/GeneratedTextWidget2.dart';
import 'package:flutterapp/woxisapp/generatedantrenmandetaylar2widget/generated/Generated5Widget1.dart';
import 'package:flutterapp/woxisapp/generatedantrenmandetaylar2widget/generated/GeneratedSpotterWidget1.dart';

/* Frame Antrenman Detayları 2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAntrenmanDetaylar2Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 44.0,
                child: GeneratedIOSStatusBarBlackWidget6(),
              ),
              Positioned(
                left: 16.0,
                top: 136.0,
                right: 16.0,
                bottom: null,
                width: null,
                height: 36.0,
                child: GeneratedPageHeaderWidget6(),
              ),
              Positioned(
                left: null,
                top: null,
                right: null,
                bottom: 579.0,
                width: 123.0,
                height: 21.0,
                child: TransformHelper.translate(
                    x: -108.00,
                    y: 0.00,
                    z: 0,
                    child: GeneratedalmaArlWidget1()),
              ),
              Positioned(
                left: 18.0,
                top: 270.0,
                right: null,
                bottom: null,
                width: 317.5035400390625,
                height: 0.0,
                child: GeneratedVector1Widget2(),
              ),
              Positioned(
                left: 18.0,
                top: 246.0,
                right: null,
                bottom: null,
                width: 47.0,
                height: 21.0,
                child: Generated35KgWidget1(),
              ),
              Positioned(
                left: null,
                top: null,
                right: null,
                bottom: 243.0,
                width: 2.0,
                height: 21.0,
                child: TransformHelper.translate(
                    x: -168.50, y: 0.00, z: 0, child: GeneratedTextWidget2()),
              ),
              Positioned(
                left: null,
                top: null,
                right: null,
                bottom: 499.0,
                width: 102.0,
                height: 21.0,
                child: TransformHelper.translate(
                    x: -118.50,
                    y: 0.00,
                    z: 0,
                    child: GeneratedTekrarSaysWidget1()),
              ),
              Positioned(
                left: 18.0,
                top: 350.0,
                right: null,
                bottom: null,
                width: 317.5035400390625,
                height: 0.0,
                child: GeneratedVector2Widget2(),
              ),
              Positioned(
                left: 18.0,
                top: 326.0,
                right: null,
                bottom: null,
                width: 16.0,
                height: 24.0,
                child: Generated8Widget1(),
              ),
              Positioned(
                left: null,
                top: null,
                right: null,
                bottom: 410.0,
                width: 64.0,
                height: 24.0,
                child: TransformHelper.translate(
                    x: -137.50,
                    y: 0.00,
                    z: 0,
                    child: GeneratedSpotterWidget1()),
              ),
              Positioned(
                left: 20.0,
                top: 448.0,
                right: null,
                bottom: null,
                width: 318.0,
                height: 0.0,
                child: GeneratedVector3Widget2(),
              ),
              Positioned(
                left: 18.0,
                top: 412.0,
                right: null,
                bottom: null,
                width: 29.0,
                height: 24.0,
                child: Generated5Widget1(),
              ),
              Positioned(
                left: 16.0,
                top: null,
                right: 16.0,
                bottom: 46.0,
                width: null,
                height: 51.0,
                child: GeneratedButtonPrimaryWidget7(),
              ),
              Positioned(
                left: 62.0,
                top: 439.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 17.0,
                child: GeneratedGroup13Widget1(),
              ),
              Positioned(
                left: 119.0,
                top: 45.0,
                right: null,
                bottom: null,
                width: 138.0,
                height: 41.0,
                child: GeneratedWOXIS_SIYAH1Widget5(),
              )
            ]),
      ),
    ));
  }
}
