import 'package:flutter/material.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/woxisapp/generatedqrkodantrenmanwidget/generated/GeneratedGroup1Widget1.dart';
import 'package:flutterapp/woxisapp/generatedqrkodantrenmanwidget/generated/GeneratedstasyonEkranndaBulunanQRKoduokutunWidget1.dart';
import 'package:flutterapp/woxisapp/generatedqrkodantrenmanwidget/generated/GeneratedButtonPrimaryWidget29.dart';
import 'package:flutterapp/woxisapp/generatedqrkodantrenmanwidget/generated/GeneratedIOSStatusBarBlackWidget20.dart';
import 'package:flutterapp/woxisapp/generatedqrkodantrenmanwidget/generated/GeneratedWOXIS_SIYAH1Widget16.dart';
import 'package:flutterapp/woxisapp/generatedqrkodantrenmanwidget/generated/GeneratedPageHeaderWidget14.dart';

/* Frame QR Kod/Antrenman
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedQRKodAntrenmanWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 44.0,
                child: GeneratedIOSStatusBarBlackWidget20(),
              ),
              Positioned(
                left: 13.0,
                top: 130.0,
                right: 19.0,
                bottom: null,
                width: null,
                height: 36.0,
                child: GeneratedPageHeaderWidget14(),
              ),
              Positioned(
                left: null,
                top: null,
                right: null,
                bottom: 262.0,
                width: 243.0,
                height: 46.0,
                child: TransformHelper.translate(
                    x: -5.00,
                    y: 0.00,
                    z: 0,
                    child:
                        GeneratedstasyonEkranndaBulunanQRKoduokutunWidget1()),
              ),
              Positioned(
                left: 59.0,
                top: 208.0,
                right: null,
                bottom: null,
                width: 254.0,
                height: 254.0,
                child: GeneratedGroup1Widget1(),
              ),
              Positioned(
                left: 13.0,
                top: null,
                right: 19.0,
                bottom: 29.0,
                width: null,
                height: 51.0,
                child: GeneratedButtonPrimaryWidget29(),
              ),
              Positioned(
                left: 116.0,
                top: 45.0,
                right: null,
                bottom: null,
                width: 138.0,
                height: 41.0,
                child: GeneratedWOXIS_SIYAH1Widget16(),
              )
            ]),
      ),
    ));
  }
}
