import 'package:flutter/material.dart';
import 'package:flutterapp/woxisapp/generatedhedefbelirlewidget/generated/GeneratedIOSStatusBarBlackWidget9.dart';
import 'package:flutterapp/woxisapp/generatedhedefbelirlewidget/generated/Generated12gnWidget.dart';
import 'package:flutterapp/woxisapp/generatedhedefbelirlewidget/generated/GeneratedYayakmWidget.dart';
import 'package:flutterapp/woxisapp/generatedhedefbelirlewidget/generated/Generated35gnWidget.dart';
import 'package:flutterapp/woxisapp/generatedhedefbelirlewidget/generated/GeneratedSklamaWidget.dart';
import 'package:flutterapp/woxisapp/generatedhedefbelirlewidget/generated/GeneratedVector4Widget2.dart';
import 'package:flutterapp/woxisapp/generatedhedefbelirlewidget/generated/GeneratedButtonPrimaryWidget10.dart';
import 'package:flutterapp/woxisapp/generatedhedefbelirlewidget/generated/GeneratedVector8Widget.dart';
import 'package:flutterapp/woxisapp/generatedhedefbelirlewidget/generated/GeneratedAntrenmanhedefinnedirWidget.dart';
import 'package:flutterapp/woxisapp/generatedhedefbelirlewidget/generated/GeneratedPageHeaderWidget9.dart';
import 'package:flutterapp/woxisapp/generatedhedefbelirlewidget/generated/GeneratedKasgeliimiWidget.dart';
import 'package:flutterapp/woxisapp/generatedhedefbelirlewidget/generated/GeneratedVector7Widget.dart';
import 'package:flutterapp/woxisapp/generatedhedefbelirlewidget/generated/GeneratedVector9Widget.dart';
import 'package:flutterapp/woxisapp/generatedhedefbelirlewidget/generated/GeneratedVector6Widget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/woxisapp/generatedhedefbelirlewidget/generated/GeneratedYenibalayanWidget.dart';
import 'package:flutterapp/woxisapp/generatedhedefbelirlewidget/generated/GeneratedHaftalkantrenmansrennedirWidget.dart';
import 'package:flutterapp/woxisapp/generatedhedefbelirlewidget/generated/GeneratedVector5Widget.dart';
import 'package:flutterapp/woxisapp/generatedhedefbelirlewidget/generated/Generated67gnWidget.dart';
import 'package:flutterapp/woxisapp/generatedhedefbelirlewidget/generated/GeneratedVector10Widget.dart';

/* Frame Hedef Belirle
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHedefBelirleWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 44.0,
                child: GeneratedIOSStatusBarBlackWidget9(),
              ),
              Positioned(
                left: 16.0,
                top: 60.0,
                right: 16.0,
                bottom: null,
                width: null,
                height: 36.0,
                child: GeneratedPageHeaderWidget9(),
              ),
              Positioned(
                left: null,
                top: null,
                right: null,
                bottom: 658.0,
                width: 204.0,
                height: 21.0,
                child: TransformHelper.translate(
                    x: -67.50,
                    y: 0.00,
                    z: 0,
                    child: GeneratedAntrenmanhedefinnedirWidget()),
              ),
              Positioned(
                left: 18.0,
                top: 191.0,
                right: null,
                bottom: null,
                width: 317.5035400390625,
                height: 0.0,
                child: GeneratedVector4Widget2(),
              ),
              Positioned(
                left: 18.0,
                top: 167.0,
                right: null,
                bottom: null,
                width: 85.0,
                height: 21.0,
                child: GeneratedYayakmWidget(),
              ),
              Positioned(
                left: 18.0,
                top: 246.0,
                right: null,
                bottom: null,
                width: 317.5035400390625,
                height: 0.0,
                child: GeneratedVector5Widget(),
              ),
              Positioned(
                left: 18.0,
                top: 222.0,
                right: null,
                bottom: null,
                width: 79.0,
                height: 24.0,
                child: GeneratedSklamaWidget(),
              ),
              Positioned(
                left: 18.0,
                top: 301.0,
                right: null,
                bottom: null,
                width: 317.5035400390625,
                height: 0.0,
                child: GeneratedVector6Widget(),
              ),
              Positioned(
                left: 18.0,
                top: 277.0,
                right: null,
                bottom: null,
                width: 95.0,
                height: 21.0,
                child: GeneratedKasgeliimiWidget(),
              ),
              Positioned(
                left: null,
                top: null,
                right: null,
                bottom: 374.0,
                width: 250.0,
                height: 21.0,
                child: TransformHelper.translate(
                    x: -44.50,
                    y: 0.00,
                    z: 0,
                    child: GeneratedHaftalkantrenmansrennedirWidget()),
              ),
              Positioned(
                left: 18.0,
                top: 475.0,
                right: null,
                bottom: null,
                width: 317.5035400390625,
                height: 0.0,
                child: GeneratedVector7Widget(),
              ),
              Positioned(
                left: 18.0,
                top: 451.0,
                right: null,
                bottom: null,
                width: 67.0,
                height: 21.0,
                child: Generated67gnWidget(),
              ),
              Positioned(
                left: 18.0,
                top: 530.0,
                right: null,
                bottom: null,
                width: 317.5035400390625,
                height: 0.0,
                child: GeneratedVector8Widget(),
              ),
              Positioned(
                left: 18.0,
                top: 506.0,
                right: null,
                bottom: null,
                width: 64.0,
                height: 21.0,
                child: Generated35gnWidget(),
              ),
              Positioned(
                left: 18.0,
                top: 585.0,
                right: null,
                bottom: null,
                width: 317.5035400390625,
                height: 0.0,
                child: GeneratedVector9Widget(),
              ),
              Positioned(
                left: 18.0,
                top: 561.0,
                right: null,
                bottom: null,
                width: 61.0,
                height: 21.0,
                child: Generated12gnWidget(),
              ),
              Positioned(
                left: 18.0,
                top: 634.0,
                right: null,
                bottom: null,
                width: 317.5035400390625,
                height: 0.0,
                child: GeneratedVector10Widget(),
              ),
              Positioned(
                left: 18.0,
                top: 610.0,
                right: null,
                bottom: null,
                width: 109.0,
                height: 21.0,
                child: GeneratedYenibalayanWidget(),
              ),
              Positioned(
                left: 16.0,
                top: null,
                right: 16.0,
                bottom: 46.0,
                width: null,
                height: 51.0,
                child: GeneratedButtonPrimaryWidget10(),
              )
            ]),
      ),
    ));
  }
}
