import 'package:flutter/material.dart';
import 'package:flutterapp/woxisapp/generatedantrenmantipi2widget/generated/GeneratedWOXIS_SIYAH1Widget12.dart';
import 'package:flutterapp/woxisapp/generatedantrenmantipi2widget/generated/GeneratedGroup12Widget.dart';
import 'package:flutterapp/woxisapp/generatedantrenmantipi2widget/generated/GeneratedIOSStatusBarBlackWidget15.dart';
import 'package:flutterapp/woxisapp/generatedantrenmantipi2widget/generated/GeneratedGroup3Widget1.dart';
import 'package:flutterapp/woxisapp/generatedantrenmantipi2widget/generated/GeneratedGroup11Widget.dart';
import 'package:flutterapp/woxisapp/generatedantrenmantipi2widget/generated/GeneratedGroup10Widget.dart';

/* Frame Antrenman Tipi 2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAntrenmanTipi2Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 44.0,
                child: GeneratedIOSStatusBarBlackWidget15(),
              ),
              Positioned(
                left: 115.0,
                top: 45.0,
                right: null,
                bottom: null,
                width: 138.0,
                height: 41.0,
                child: GeneratedWOXIS_SIYAH1Widget12(),
              ),
              Positioned(
                left: 16.0,
                top: 52.0,
                right: null,
                bottom: null,
                width: 17.731151580810547,
                height: 27.733333587646484,
                child: GeneratedGroup3Widget1(),
              ),
              Positioned(
                left: 16.0,
                top: 106.0,
                right: null,
                bottom: null,
                width: 344.220458984375,
                height: 206.35714721679688,
                child: GeneratedGroup10Widget(),
              ),
              Positioned(
                left: 16.0,
                top: 323.0,
                right: null,
                bottom: null,
                width: 344.262939453125,
                height: 207.17868041992188,
                child: GeneratedGroup11Widget(),
              ),
              Positioned(
                left: 16.0,
                top: 540.0,
                right: null,
                bottom: null,
                width: 344.262939453125,
                height: 207.99996948242188,
                child: GeneratedGroup12Widget(),
              )
            ]),
      ),
    ));
  }
}
