import 'package:flutter/material.dart';
import 'package:flutterapp/woxisapp/generatedantrenmankaydetme2widget/generated/GeneratedGroup6Widget4.dart';
import 'package:flutterapp/woxisapp/generatedantrenmankaydetme2widget/generated/GeneratedAntrenmanAdWidget1.dart';
import 'package:flutterapp/woxisapp/generatedantrenmankaydetme2widget/generated/GeneratedButtonPrimaryWidget11.dart';
import 'package:flutterapp/woxisapp/generatedantrenmankaydetme2widget/generated/GeneratedVector4Widget4.dart';
import 'package:flutterapp/woxisapp/generatedantrenmankaydetme2widget/generated/GeneratedWOXIS_SIYAH1Widget8.dart';
import 'package:flutterapp/woxisapp/generatedantrenmankaydetme2widget/generated/GeneratedPageHeaderWidget11.dart';
import 'package:flutterapp/woxisapp/generatedantrenmankaydetme2widget/generated/GeneratedSerbestIncline35KgWidget1.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/woxisapp/generatedantrenmankaydetme2widget/generated/GeneratedIOSStatusBarBlackWidget11.dart';

/* Frame Antrenman Kaydetme 2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAntrenmanKaydetme2Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 44.0,
                child: GeneratedIOSStatusBarBlackWidget11(),
              ),
              Positioned(
                left: 16.0,
                top: 114.0,
                right: 16.0,
                bottom: null,
                width: null,
                height: 36.0,
                child: GeneratedPageHeaderWidget11(),
              ),
              Positioned(
                left: null,
                top: null,
                right: null,
                bottom: 604.0,
                width: 118.0,
                height: 21.0,
                child: TransformHelper.translate(
                    x: -110.50,
                    y: 0.00,
                    z: 0,
                    child: GeneratedAntrenmanAdWidget1()),
              ),
              Positioned(
                left: 18.0,
                top: 245.0,
                right: null,
                bottom: null,
                width: 317.5035400390625,
                height: 0.0,
                child: GeneratedVector4Widget4(),
              ),
              Positioned(
                left: 18.0,
                top: 221.0,
                right: null,
                bottom: null,
                width: 315.0,
                height: 22.0,
                child: GeneratedSerbestIncline35KgWidget1(),
              ),
              Positioned(
                left: 16.0,
                top: null,
                right: 16.0,
                bottom: 46.0,
                width: null,
                height: 51.0,
                child: GeneratedButtonPrimaryWidget11(),
              ),
              Positioned(
                left: 13.0,
                top: 55.0,
                right: null,
                bottom: null,
                width: 17.731151580810547,
                height: 27.733333587646484,
                child: GeneratedGroup6Widget4(),
              ),
              Positioned(
                left: 117.0,
                top: 48.0,
                right: null,
                bottom: null,
                width: 138.0,
                height: 41.0,
                child: GeneratedWOXIS_SIYAH1Widget8(),
              )
            ]),
      ),
    ));
  }
}
