import 'package:flutter/material.dart';
import 'package:flutterapp/woxisapp/generatedkiiselbilgileralternatifwidget/generated/GeneratedVector3Widget4.dart';
import 'package:flutterapp/woxisapp/generatedkiiselbilgileralternatifwidget/generated/Generated179cmWidget1.dart';
import 'package:flutterapp/woxisapp/generatedkiiselbilgileralternatifwidget/generated/GeneratedIOSStatusBarBlackWidget8.dart';
import 'package:flutterapp/woxisapp/generatedkiiselbilgileralternatifwidget/generated/GeneratedArlkWidget1.dart';
import 'package:flutterapp/woxisapp/generatedkiiselbilgileralternatifwidget/generated/GeneratedlkeWidget1.dart';
import 'package:flutterapp/woxisapp/generatedkiiselbilgileralternatifwidget/generated/GeneratedSegmentedControlLeftWidget.dart';
import 'package:flutterapp/woxisapp/generatedkiiselbilgileralternatifwidget/generated/GeneratedBoyWidget1.dart';
import 'package:flutterapp/woxisapp/generatedkiiselbilgileralternatifwidget/generated/GeneratedVector1Widget4.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/woxisapp/generatedkiiselbilgileralternatifwidget/generated/GeneratedTrkiyeWidget1.dart';
import 'package:flutterapp/woxisapp/generatedkiiselbilgileralternatifwidget/generated/GeneratedVector2Widget4.dart';
import 'package:flutterapp/woxisapp/generatedkiiselbilgileralternatifwidget/generated/GeneratedCinsiyetWidget1.dart';
import 'package:flutterapp/woxisapp/generatedkiiselbilgileralternatifwidget/generated/GeneratedDoumTarihiWidget1.dart';
import 'package:flutterapp/woxisapp/generatedkiiselbilgileralternatifwidget/generated/GeneratedPageHeaderWidget8.dart';
import 'package:flutterapp/woxisapp/generatedkiiselbilgileralternatifwidget/generated/GeneratedVector4Widget1.dart';
import 'package:flutterapp/woxisapp/generatedkiiselbilgileralternatifwidget/generated/Generated72kgWidget1.dart';
import 'package:flutterapp/woxisapp/generatedkiiselbilgileralternatifwidget/generated/Generated01061985Widget1.dart';
import 'package:flutterapp/woxisapp/generatedkiiselbilgileralternatifwidget/generated/GeneratedButtonPrimaryWidget9.dart';

/* Frame Kişisel Bilgiler/alternatif
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedKiiselBilgileralternatifWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 25, 25, 25),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 44.0,
                child: GeneratedIOSStatusBarBlackWidget8(),
              ),
              Positioned(
                left: 16.0,
                top: 60.0,
                right: 16.0,
                bottom: null,
                width: null,
                height: 36.0,
                child: GeneratedPageHeaderWidget8(),
              ),
              Positioned(
                left: null,
                top: null,
                right: null,
                bottom: 655.0,
                width: 114.0,
                height: 21.0,
                child: TransformHelper.translate(
                    x: -112.50,
                    y: 0.00,
                    z: 0,
                    child: GeneratedDoumTarihiWidget1()),
              ),
              Positioned(
                left: null,
                top: null,
                right: null,
                bottom: 394.0,
                width: 77.0,
                height: 24.0,
                child: TransformHelper.translate(
                    x: 7.00, y: 0.00, z: 0, child: GeneratedCinsiyetWidget1()),
              ),
              Positioned(
                left: 18.0,
                top: 194.0,
                right: null,
                bottom: null,
                width: 317.5035400390625,
                height: 0.0,
                child: GeneratedVector1Widget4(),
              ),
              Positioned(
                left: 18.0,
                top: 170.0,
                right: null,
                bottom: null,
                width: 96.0,
                height: 24.0,
                child: Generated01061985Widget1(),
              ),
              Positioned(
                left: null,
                top: null,
                right: null,
                bottom: 240.0,
                width: 40.0,
                height: 24.0,
                child: TransformHelper.translate(
                    x: -149.50, y: 0.00, z: 0, child: GeneratedlkeWidget1()),
              ),
              Positioned(
                left: 18.0,
                top: 606.0,
                right: null,
                bottom: null,
                width: 317.5035400390625,
                height: 0.0,
                child: GeneratedVector4Widget1(),
              ),
              Positioned(
                left: 18.0,
                top: 582.0,
                right: null,
                bottom: null,
                width: 63.0,
                height: 24.0,
                child: GeneratedTrkiyeWidget1(),
              ),
              Positioned(
                left: null,
                top: null,
                right: null,
                bottom: 572.0,
                width: 63.0,
                height: 24.0,
                child: TransformHelper.translate(
                    x: -138.00, y: 0.00, z: 0, child: GeneratedArlkWidget1()),
              ),
              Positioned(
                left: 18.0,
                top: 274.0,
                right: null,
                bottom: null,
                width: 317.5035400390625,
                height: 0.0,
                child: GeneratedVector2Widget4(),
              ),
              Positioned(
                left: 18.0,
                top: 250.0,
                right: null,
                bottom: null,
                width: 45.0,
                height: 21.0,
                child: Generated72kgWidget1(),
              ),
              Positioned(
                left: null,
                top: null,
                right: null,
                bottom: 486.0,
                width: 43.0,
                height: 24.0,
                child: TransformHelper.translate(
                    x: -148.00, y: 0.00, z: 0, child: GeneratedBoyWidget1()),
              ),
              Positioned(
                left: 18.0,
                top: 360.0,
                right: null,
                bottom: null,
                width: 318.0,
                height: 0.0,
                child: GeneratedVector3Widget4(),
              ),
              Positioned(
                left: 18.0,
                top: 336.0,
                right: null,
                bottom: null,
                width: 57.0,
                height: 21.0,
                child: Generated179cmWidget1(),
              ),
              Positioned(
                left: 16.0,
                top: null,
                right: 16.0,
                bottom: 23.0,
                width: null,
                height: 51.0,
                child: GeneratedButtonPrimaryWidget9(),
              ),
              Positioned(
                left: 66.0,
                top: 444.0,
                right: 72.0,
                bottom: null,
                width: null,
                height: 50.0,
                child: GeneratedSegmentedControlLeftWidget(),
              )
            ]),
      ),
    ));
  }
}
