import 'package:flutter/material.dart';
import 'package:flutterapp/woxisapp/generatedgiriyapwidget1/generated/GeneratedifremiunuttumWidget1.dart';
import 'package:flutterapp/woxisapp/generatedgiriyapwidget1/generated/GeneratedIOSStatusBarBlackWidget1.dart';
import 'package:flutterapp/woxisapp/generatedgiriyapwidget1/generated/GeneratedInputTextWidget4.dart';
import 'package:flutterapp/woxisapp/generatedgiriyapwidget1/generated/GeneratedPageHeaderWidget1.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/woxisapp/generatedgiriyapwidget1/generated/GeneratedWOXIS_SIYAH1Widget1.dart';
import 'package:flutterapp/woxisapp/generatedgiriyapwidget1/generated/GeneratedInputTextWidget3.dart';
import 'package:flutterapp/woxisapp/generatedgiriyapwidget1/generated/GeneratedButtonPrimaryWidget1.dart';
import 'package:flutterapp/woxisapp/generatedgiriyapwidget1/generated/GeneratedIOSKeyboardLightAlphabeticWidget1.dart';

/* Frame Giriş Yap
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedGiriYapWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 44.0,
                child: GeneratedIOSStatusBarBlackWidget1(),
              ),
              Positioned(
                left: 16.0,
                top: null,
                right: 16.0,
                bottom: 350.0,
                width: null,
                height: 51.0,
                child: GeneratedButtonPrimaryWidget1(),
              ),
              Positioned(
                left: null,
                top: null,
                right: null,
                bottom: 309.0,
                width: 127.0,
                height: 21.0,
                child: TransformHelper.translate(
                    x: 9.00,
                    y: 0.00,
                    z: 0,
                    child: GeneratedifremiunuttumWidget1()),
              ),
              Positioned(
                left: null,
                top: null,
                right: null,
                bottom: 0.0,
                width: 375.0,
                height: 291.0,
                child: GeneratedIOSKeyboardLightAlphabeticWidget1(),
              ),
              Positioned(
                left: 119.0,
                top: 45.0,
                right: null,
                bottom: null,
                width: 138.0,
                height: 41.0,
                child: GeneratedWOXIS_SIYAH1Widget1(),
              ),
              Positioned(
                left: 16.0,
                top: 115.0,
                right: 16.0,
                bottom: null,
                width: null,
                height: 36.0,
                child: GeneratedPageHeaderWidget1(),
              ),
              Positioned(
                left: 16.0,
                top: 167.0,
                right: 16.0,
                bottom: null,
                width: null,
                height: 50.0,
                child: GeneratedInputTextWidget3(),
              ),
              Positioned(
                left: 16.0,
                top: 233.0,
                right: 16.0,
                bottom: null,
                width: null,
                height: 50.0,
                child: GeneratedInputTextWidget4(),
              )
            ]),
      ),
    ));
  }
}
