import 'package:flutter/material.dart';
import 'package:flutterapp/woxisapp/generatedkaytolwidget/generated/GeneratedIOSKeyboardLightAlphabeticWidget.dart';
import 'package:flutterapp/woxisapp/generatedkaytolwidget/generated/GeneratedInputTextWidget.dart';
import 'package:flutterapp/woxisapp/generatedkaytolwidget/generated/GeneratedifremiunuttumWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/woxisapp/generatedkaytolwidget/generated/GeneratedButtonPrimaryWidget.dart';
import 'package:flutterapp/woxisapp/generatedkaytolwidget/generated/GeneratedInputTextWidget1.dart';
import 'package:flutterapp/woxisapp/generatedkaytolwidget/generated/GeneratedIOSStatusBarBlackWidget.dart';
import 'package:flutterapp/woxisapp/generatedkaytolwidget/generated/GeneratedInputTextWidget2.dart';
import 'package:flutterapp/woxisapp/generatedkaytolwidget/generated/GeneratedPageHeaderWidget.dart';
import 'package:flutterapp/woxisapp/generatedkaytolwidget/generated/GeneratedWOXIS_SIYAH1Widget.dart';
import 'package:flutterapp/woxisapp/generatedkaytolwidget/generated/GeneratedCheckboxOptionEmptyWidget.dart';

/* Frame Kayıt Ol
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedKaytOlWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 44.0,
                child: GeneratedIOSStatusBarBlackWidget(),
              ),
              Positioned(
                left: 16.0,
                top: 114.0,
                right: 16.0,
                bottom: null,
                width: null,
                height: 36.0,
                child: GeneratedPageHeaderWidget(),
              ),
              Positioned(
                left: 16.0,
                top: 167.0,
                right: 16.0,
                bottom: null,
                width: null,
                height: 50.0,
                child: GeneratedInputTextWidget(),
              ),
              Positioned(
                left: 16.0,
                top: 233.0,
                right: 16.0,
                bottom: null,
                width: null,
                height: 50.0,
                child: GeneratedInputTextWidget1(),
              ),
              Positioned(
                left: 16.0,
                top: 299.0,
                right: 16.0,
                bottom: null,
                width: null,
                height: 50.0,
                child: GeneratedInputTextWidget2(),
              ),
              Positioned(
                left: null,
                top: null,
                right: null,
                bottom: 0.0,
                width: 375.0,
                height: 291.0,
                child: GeneratedIOSKeyboardLightAlphabeticWidget(),
              ),
              Positioned(
                left: 16.0,
                top: null,
                right: 16.0,
                bottom: 342.0,
                width: null,
                height: 51.0,
                child: GeneratedButtonPrimaryWidget(),
              ),
              Positioned(
                left: null,
                top: null,
                right: null,
                bottom: 305.0,
                width: 127.0,
                height: 21.0,
                child: TransformHelper.translate(
                    x: 14.00,
                    y: 0.00,
                    z: 0,
                    child: GeneratedifremiunuttumWidget()),
              ),
              Positioned(
                left: 111.0,
                top: 45.0,
                right: null,
                bottom: null,
                width: 138.0,
                height: 41.0,
                child: GeneratedWOXIS_SIYAH1Widget(),
              ),
              Positioned(
                left: 16.0,
                top: 370.0,
                right: 16.0,
                bottom: null,
                width: null,
                height: 17.0,
                child: GeneratedCheckboxOptionEmptyWidget(),
              )
            ]),
      ),
    ));
  }
}
