import 'package:flutter/material.dart';
import 'package:flutterapp/woxisapp/generatedkiiselbilgilerwidget/generated/GeneratedArlkWidget.dart';
import 'package:flutterapp/woxisapp/generatedkiiselbilgilerwidget/generated/GeneratedButtonPrimaryWidget4.dart';
import 'package:flutterapp/woxisapp/generatedkiiselbilgilerwidget/generated/GeneratedErkekWidget1.dart';
import 'package:flutterapp/woxisapp/generatedkiiselbilgilerwidget/generated/GeneratedTrkiyeWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/woxisapp/generatedkiiselbilgilerwidget/generated/GeneratedKadnWidget.dart';
import 'package:flutterapp/woxisapp/generatedkiiselbilgilerwidget/generated/GeneratedCinsiyetWidget.dart';
import 'package:flutterapp/woxisapp/generatedkiiselbilgilerwidget/generated/GeneratedVector3Widget.dart';
import 'package:flutterapp/woxisapp/generatedkiiselbilgilerwidget/generated/GeneratedDoumTarihiWidget.dart';
import 'package:flutterapp/woxisapp/generatedkiiselbilgilerwidget/generated/Generated01061985Widget.dart';
import 'package:flutterapp/woxisapp/generatedkiiselbilgilerwidget/generated/GeneratedVector2Widget.dart';
import 'package:flutterapp/woxisapp/generatedkiiselbilgilerwidget/generated/GeneratedPageHeaderWidget4.dart';
import 'package:flutterapp/woxisapp/generatedkiiselbilgilerwidget/generated/GeneratedlkeWidget.dart';
import 'package:flutterapp/woxisapp/generatedkiiselbilgilerwidget/generated/Generated179cmWidget.dart';
import 'package:flutterapp/woxisapp/generatedkiiselbilgilerwidget/generated/GeneratedGroupWidget2.dart';
import 'package:flutterapp/woxisapp/generatedkiiselbilgilerwidget/generated/GeneratedVectorWidget1.dart';
import 'package:flutterapp/woxisapp/generatedkiiselbilgilerwidget/generated/Generated72kgWidget.dart';
import 'package:flutterapp/woxisapp/generatedkiiselbilgilerwidget/generated/GeneratedVector4Widget.dart';
import 'package:flutterapp/woxisapp/generatedkiiselbilgilerwidget/generated/GeneratedErkekWidget.dart';
import 'package:flutterapp/woxisapp/generatedkiiselbilgilerwidget/generated/GeneratedBoyWidget.dart';
import 'package:flutterapp/woxisapp/generatedkiiselbilgilerwidget/generated/GeneratedVector1Widget.dart';
import 'package:flutterapp/woxisapp/generatedkiiselbilgilerwidget/generated/GeneratedVectorWidget2.dart';
import 'package:flutterapp/woxisapp/generatedkiiselbilgilerwidget/generated/GeneratedVectorWidget5.dart';
import 'package:flutterapp/woxisapp/generatedkiiselbilgilerwidget/generated/GeneratedTextWidget.dart';
import 'package:flutterapp/woxisapp/generatedkiiselbilgilerwidget/generated/GeneratedGroupWidget.dart';
import 'package:flutterapp/woxisapp/generatedkiiselbilgilerwidget/generated/GeneratedIOSStatusBarBlackWidget4.dart';
import 'package:flutterapp/woxisapp/generatedkiiselbilgilerwidget/generated/GeneratedVectorWidget4.dart';
import 'package:flutterapp/woxisapp/generatedkiiselbilgilerwidget/generated/GeneratedKadnWidget1.dart';

/* Frame Kişisel Bilgiler
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedKiiselBilgilerWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 44.0,
                child: GeneratedIOSStatusBarBlackWidget4(),
              ),
              Positioned(
                left: 16.0,
                top: 60.0,
                right: 16.0,
                bottom: null,
                width: null,
                height: 36.0,
                child: GeneratedPageHeaderWidget4(),
              ),
              Positioned(
                left: null,
                top: null,
                right: null,
                bottom: 655.0,
                width: 114.0,
                height: 21.0,
                child: TransformHelper.translate(
                    x: -112.50,
                    y: 0.00,
                    z: 0,
                    child: GeneratedDoumTarihiWidget()),
              ),
              Positioned(
                left: null,
                top: null,
                right: null,
                bottom: 394.0,
                width: 77.0,
                height: 24.0,
                child: TransformHelper.translate(
                    x: 7.00, y: 0.00, z: 0, child: GeneratedCinsiyetWidget()),
              ),
              Positioned(
                left: 18.0,
                top: 194.0,
                right: null,
                bottom: null,
                width: 317.5035400390625,
                height: 0.0,
                child: GeneratedVector1Widget(),
              ),
              Positioned(
                left: 18.0,
                top: 170.0,
                right: null,
                bottom: null,
                width: 96.0,
                height: 24.0,
                child: Generated01061985Widget(),
              ),
              Positioned(
                left: null,
                top: null,
                right: null,
                bottom: 243.0,
                width: 2.0,
                height: 21.0,
                child: TransformHelper.translate(
                    x: -168.50, y: 0.00, z: 0, child: GeneratedTextWidget()),
              ),
              Positioned(
                left: 18.0,
                top: 606.0,
                right: null,
                bottom: null,
                width: 317.5035400390625,
                height: 0.0,
                child: GeneratedVector4Widget(),
              ),
              Positioned(
                left: 18.0,
                top: 582.0,
                right: null,
                bottom: null,
                width: 63.0,
                height: 24.0,
                child: GeneratedTrkiyeWidget(),
              ),
              Positioned(
                left: null,
                top: null,
                right: null,
                bottom: 572.0,
                width: 63.0,
                height: 24.0,
                child: TransformHelper.translate(
                    x: -138.00, y: 0.00, z: 0, child: GeneratedArlkWidget()),
              ),
              Positioned(
                left: 18.0,
                top: 274.0,
                right: null,
                bottom: null,
                width: 317.5035400390625,
                height: 0.0,
                child: GeneratedVector2Widget(),
              ),
              Positioned(
                left: 18.0,
                top: 250.0,
                right: null,
                bottom: null,
                width: 45.0,
                height: 21.0,
                child: Generated72kgWidget(),
              ),
              Positioned(
                left: null,
                top: null,
                right: null,
                bottom: 486.0,
                width: 43.0,
                height: 24.0,
                child: TransformHelper.translate(
                    x: -148.00, y: 0.00, z: 0, child: GeneratedBoyWidget()),
              ),
              Positioned(
                left: null,
                top: null,
                right: null,
                bottom: 239.0,
                width: 40.0,
                height: 24.0,
                child: TransformHelper.translate(
                    x: -149.50, y: 0.00, z: 0, child: GeneratedlkeWidget()),
              ),
              Positioned(
                left: 18.0,
                top: 360.0,
                right: null,
                bottom: null,
                width: 318.0,
                height: 0.0,
                child: GeneratedVector3Widget(),
              ),
              Positioned(
                left: 18.0,
                top: 336.0,
                right: null,
                bottom: null,
                width: 57.0,
                height: 21.0,
                child: Generated179cmWidget(),
              ),
              Positioned(
                left: 16.0,
                top: null,
                right: 16.0,
                bottom: 46.0,
                width: null,
                height: 51.0,
                child: GeneratedButtonPrimaryWidget4(),
              ),
              Positioned(
                left: null,
                top: null,
                right: null,
                bottom: 344.0,
                width: 48.0,
                height: 24.0,
                child: TransformHelper.translate(
                    x: -114.50, y: 0.00, z: 0, child: GeneratedKadnWidget()),
              ),
              Positioned(
                left: null,
                top: null,
                right: null,
                bottom: 344.0,
                width: 47.0,
                height: 24.0,
                child: TransformHelper.translate(
                    x: 120.00, y: 0.00, z: 0, child: GeneratedErkekWidget()),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 0.208;

                  final double height =
                      constraints.maxHeight * 0.050843788485221676;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.3973333333333333,
                        y: constraints.maxHeight * 0.5283251231527094,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroupWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.072;
                  double scaleX = (constraints.maxWidth * percentWidth) / 27.0;

                  double percentHeight = 0.05295566502463054;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 43.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.27466666666666667,
                        translateY: constraints.maxHeight * 0.5283251231527094,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget1())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.06666666666666667;
                  double scaleX = (constraints.maxWidth * percentWidth) / 25.0;

                  double percentHeight = 0.05295566502463054;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 43.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.7226666666666667,
                        translateY: constraints.maxHeight * 0.5283251231527094,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget2())
                  ]);
                }),
              ),
              Positioned(
                left: null,
                top: null,
                right: null,
                bottom: 344.0,
                width: 48.0,
                height: 24.0,
                child: TransformHelper.translate(
                    x: -114.50, y: 0.00, z: 0, child: GeneratedKadnWidget1()),
              ),
              Positioned(
                left: null,
                top: null,
                right: null,
                bottom: 344.0,
                width: 47.0,
                height: 24.0,
                child: TransformHelper.translate(
                    x: 120.00, y: 0.00, z: 0, child: GeneratedErkekWidget1()),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 0.208;

                  final double height =
                      constraints.maxHeight * 0.050843788485221676;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.3973333333333333,
                        y: constraints.maxHeight * 0.5283251231527094,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroupWidget2(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.072;
                  double scaleX = (constraints.maxWidth * percentWidth) / 27.0;

                  double percentHeight = 0.05295566502463054;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 43.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.27466666666666667,
                        translateY: constraints.maxHeight * 0.5283251231527094,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget4())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.06666666666666667;
                  double scaleX = (constraints.maxWidth * percentWidth) / 25.0;

                  double percentHeight = 0.05295566502463054;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 43.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.7226666666666667,
                        translateY: constraints.maxHeight * 0.5283251231527094,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget5())
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
