import 'package:flutter/material.dart';
import 'package:flutterapp/woxisapp/generatedantrenmanpozisyonusabithzlwidget/generated/GeneratedButtonPrimaryWidget24.dart';
import 'package:flutterapp/woxisapp/generatedantrenmanpozisyonusabithzlwidget/generated/GeneratedGroup5Widget.dart';
import 'package:flutterapp/woxisapp/generatedantrenmanpozisyonusabithzlwidget/generated/GeneratedButtonPrimaryWidget25.dart';
import 'package:flutterapp/woxisapp/generatedantrenmanpozisyonusabithzlwidget/generated/GeneratedIOSStatusBarBlackWidget18.dart';
import 'package:flutterapp/woxisapp/generatedantrenmanpozisyonusabithzlwidget/generated/GeneratedVectorWidget11.dart';
import 'package:flutterapp/woxisapp/generatedantrenmanpozisyonusabithzlwidget/generated/GeneratedButtonPrimaryWidget26.dart';
import 'package:flutterapp/woxisapp/generatedantrenmanpozisyonusabithzlwidget/generated/GeneratedWOXIS_SIYAH1Widget15.dart';
import 'package:flutterapp/woxisapp/generatedantrenmanpozisyonusabithzlwidget/generated/GeneratedButtonPrimaryWidget27.dart';
import 'package:flutterapp/helpers/transform/transform.dart';

/* Frame Antrenman Pozisyonu/Sabit Hızlı
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAntrenmanPozisyonuSabitHzlWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 44.0,
                child: GeneratedIOSStatusBarBlackWidget18(),
              ),
              Positioned(
                left: 115.0,
                top: 45.0,
                right: null,
                bottom: null,
                width: 138.0,
                height: 41.0,
                child: GeneratedWOXIS_SIYAH1Widget15(),
              ),
              Positioned(
                left: 13.0,
                top: null,
                right: 19.0,
                bottom: 337.0,
                width: null,
                height: 51.0,
                child: GeneratedButtonPrimaryWidget24(),
              ),
              Positioned(
                left: 13.0,
                top: null,
                right: 19.0,
                bottom: 414.0,
                width: null,
                height: 51.0,
                child: GeneratedButtonPrimaryWidget25(),
              ),
              Positioned(
                left: 13.0,
                top: null,
                right: 19.0,
                bottom: 491.0,
                width: null,
                height: 51.0,
                child: GeneratedButtonPrimaryWidget26(),
              ),
              Positioned(
                left: 13.0,
                top: null,
                right: 19.0,
                bottom: 568.0,
                width: null,
                height: 51.0,
                child: GeneratedButtonPrimaryWidget27(),
              ),
              Positioned(
                left: 13.0,
                top: 52.0,
                right: null,
                bottom: null,
                width: 17.731151580810547,
                height: 27.733333587646484,
                child: GeneratedGroup5Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.08266666666666667;
                  double scaleX = (constraints.maxWidth * percentWidth) / 31.0;

                  double percentHeight = 0.034482758620689655;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 28.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.8666666666666667,
                        translateY: constraints.maxHeight * 0.06157635467980296,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget11())
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
