import 'package:flutter/material.dart';

/* Text çöp kutusu butonu eklenecek
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedpkutusubutonueklenecekWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Text(
      '''çöp kutusu butonu eklenecek''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.center,
      style: TextStyle(
        height: 1.171875,
        fontSize: 16.0,
        fontFamily: 'Inter',
        fontWeight: FontWeight.w400,
        color: Color.fromARGB(255, 0, 0, 0),

        /* letterSpacing: 0.0, */
      ),
    ));
  }
}
