import 'package:flutter/material.dart';
import 'package:flutterapp/woxisapp/generatedantrenmankaydetme1widget/generated/GeneratedWOXIS_SIYAH1Widget7.dart';
import 'package:flutterapp/woxisapp/generatedantrenmankaydetme1widget/generated/GeneratedPageHeaderWidget10.dart';
import 'package:flutterapp/woxisapp/generatedantrenmankaydetme1widget/generated/GeneratedSerbestIncline35KgWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/woxisapp/generatedantrenmankaydetme1widget/generated/GeneratedGroup6Widget3.dart';
import 'package:flutterapp/woxisapp/generatedantrenmankaydetme1widget/generated/GeneratedIOSKeyboardLightAlphabeticWidget4.dart';
import 'package:flutterapp/woxisapp/generatedantrenmankaydetme1widget/generated/GeneratedAntrenmanAdWidget.dart';
import 'package:flutterapp/woxisapp/generatedantrenmankaydetme1widget/generated/GeneratedIOSStatusBarBlackWidget10.dart';
import 'package:flutterapp/woxisapp/generatedantrenmankaydetme1widget/generated/GeneratedVector4Widget3.dart';

/* Frame Antrenman Kaydetme 1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAntrenmanKaydetme1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 44.0,
                child: GeneratedIOSStatusBarBlackWidget10(),
              ),
              Positioned(
                left: 16.0,
                top: 114.0,
                right: 16.0,
                bottom: null,
                width: null,
                height: 36.0,
                child: GeneratedPageHeaderWidget10(),
              ),
              Positioned(
                left: null,
                top: null,
                right: null,
                bottom: 604.0,
                width: 118.0,
                height: 21.0,
                child: TransformHelper.translate(
                    x: -110.50,
                    y: 0.00,
                    z: 0,
                    child: GeneratedAntrenmanAdWidget()),
              ),
              Positioned(
                left: 18.0,
                top: 245.0,
                right: null,
                bottom: null,
                width: 317.5035400390625,
                height: 0.0,
                child: GeneratedVector4Widget3(),
              ),
              Positioned(
                left: 18.0,
                top: 221.0,
                right: null,
                bottom: null,
                width: 315.0,
                height: 22.0,
                child: GeneratedSerbestIncline35KgWidget(),
              ),
              Positioned(
                left: null,
                top: null,
                right: null,
                bottom: 0.0,
                width: 375.0,
                height: 291.0,
                child: GeneratedIOSKeyboardLightAlphabeticWidget4(),
              ),
              Positioned(
                left: 15.0,
                top: 55.0,
                right: null,
                bottom: null,
                width: 17.731151580810547,
                height: 27.733333587646484,
                child: GeneratedGroup6Widget3(),
              ),
              Positioned(
                left: 119.0,
                top: 48.0,
                right: null,
                bottom: null,
                width: 138.0,
                height: 41.0,
                child: GeneratedWOXIS_SIYAH1Widget7(),
              )
            ]),
      ),
    ));
  }
}
