import 'package:flutter/material.dart';
import 'package:flutterapp/woxisapp/generatedifremiunuttumwidget2/generated/GeneratedInputTextWidget5.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/woxisapp/generatedifremiunuttumwidget2/generated/GeneratedIOSKeyboardLightAlphabeticWidget2.dart';
import 'package:flutterapp/woxisapp/generatedifremiunuttumwidget2/generated/GeneratedPageHeaderWidget2.dart';
import 'package:flutterapp/woxisapp/generatedifremiunuttumwidget2/generated/GeneratedButtonPrimaryWidget2.dart';
import 'package:flutterapp/woxisapp/generatedifremiunuttumwidget2/generated/GeneratedifremiunuttumWidget3.dart';
import 'package:flutterapp/woxisapp/generatedifremiunuttumwidget2/generated/GeneratedWOXIS_SIYAH1Widget2.dart';
import 'package:flutterapp/woxisapp/generatedifremiunuttumwidget2/generated/GeneratedInputTextWidget6.dart';
import 'package:flutterapp/woxisapp/generatedifremiunuttumwidget2/generated/GeneratedIOSStatusBarBlackWidget2.dart';

/* Frame Şifremi unuttum :(
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedifremiunuttumWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 44.0,
                child: GeneratedIOSStatusBarBlackWidget2(),
              ),
              Positioned(
                left: 16.0,
                top: null,
                right: 16.0,
                bottom: 350.0,
                width: null,
                height: 51.0,
                child: GeneratedButtonPrimaryWidget2(),
              ),
              Positioned(
                left: null,
                top: null,
                right: null,
                bottom: 309.0,
                width: 127.0,
                height: 21.0,
                child: TransformHelper.translate(
                    x: 9.00,
                    y: 0.00,
                    z: 0,
                    child: GeneratedifremiunuttumWidget3()),
              ),
              Positioned(
                left: null,
                top: null,
                right: null,
                bottom: 0.0,
                width: 375.0,
                height: 291.0,
                child: GeneratedIOSKeyboardLightAlphabeticWidget2(),
              ),
              Positioned(
                left: 119.0,
                top: 45.0,
                right: null,
                bottom: null,
                width: 138.0,
                height: 41.0,
                child: GeneratedWOXIS_SIYAH1Widget2(),
              ),
              Positioned(
                left: 16.0,
                top: 115.0,
                right: 16.0,
                bottom: null,
                width: null,
                height: 36.0,
                child: GeneratedPageHeaderWidget2(),
              ),
              Positioned(
                left: 16.0,
                top: 167.0,
                right: 16.0,
                bottom: null,
                width: null,
                height: 50.0,
                child: GeneratedInputTextWidget5(),
              ),
              Positioned(
                left: 16.0,
                top: 233.0,
                right: 16.0,
                bottom: null,
                width: null,
                height: 50.0,
                child: GeneratedInputTextWidget6(),
              )
            ]),
      ),
    ));
  }
}
