import 'package:flutter/material.dart';
import 'package:flutterapp/woxisapp/generatedstasyonkiiselletirmewidget/generated/GeneratedIOSStatusBarBlackWidget12.dart';
import 'package:flutterapp/woxisapp/generatedstasyonkiiselletirmewidget/generated/GeneratedButtonPrimaryWidget12.dart';
import 'package:flutterapp/woxisapp/generatedstasyonkiiselletirmewidget/generated/GeneratedWOXIS_RENDER21Widget.dart';
import 'package:flutterapp/woxisapp/generatedstasyonkiiselletirmewidget/generated/GeneratedButtonPrimaryWidget13.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/woxisapp/generatedstasyonkiiselletirmewidget/generated/GeneratedAntrenrnzileberaberistasyonyannagidinizWidget.dart';
import 'package:flutterapp/woxisapp/generatedstasyonkiiselletirmewidget/generated/GeneratedPageHeaderWidget12.dart';
import 'package:flutterapp/woxisapp/generatedstasyonkiiselletirmewidget/generated/GeneratedWOXIS_SIYAH1Widget9.dart';

/* Frame İstasyon Kişiselleştirme
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedstasyonKiiselletirmeWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 44.0,
                child: GeneratedIOSStatusBarBlackWidget12(),
              ),
              Positioned(
                left: 13.0,
                top: 115.0,
                right: 19.0,
                bottom: null,
                width: null,
                height: 36.0,
                child: GeneratedPageHeaderWidget12(),
              ),
              Positioned(
                left: null,
                top: null,
                right: null,
                bottom: 180.0,
                width: 303.0,
                height: 46.0,
                child: TransformHelper.translate(
                    x: -3.00,
                    y: 0.00,
                    z: 0,
                    child:
                        GeneratedAntrenrnzileberaberistasyonyannagidinizWidget()),
              ),
              Positioned(
                left: 16.0,
                top: null,
                right: 16.0,
                bottom: 108.0,
                width: null,
                height: 51.0,
                child: GeneratedButtonPrimaryWidget12(),
              ),
              Positioned(
                left: 16.0,
                top: null,
                right: 16.0,
                bottom: 41.0,
                width: null,
                height: 51.0,
                child: GeneratedButtonPrimaryWidget13(),
              ),
              Positioned(
                left: -42.0,
                top: 174.0,
                right: null,
                bottom: null,
                width: 472.0,
                height: 353.0,
                child: GeneratedWOXIS_RENDER21Widget(),
              ),
              Positioned(
                left: 119.0,
                top: 45.0,
                right: null,
                bottom: null,
                width: 138.0,
                height: 41.0,
                child: GeneratedWOXIS_SIYAH1Widget9(),
              )
            ]),
      ),
    ));
  }
}
