import 'package:flutter/material.dart';
import 'package:flutterapp/woxisapp/generatedifreyenilemewidget/generated/GeneratedWOXIS_SIYAH1Widget3.dart';
import 'package:flutterapp/woxisapp/generatedifreyenilemewidget/generated/GeneratedIOSKeyboardLightAlphabeticWidget3.dart';
import 'package:flutterapp/woxisapp/generatedifreyenilemewidget/generated/GeneratedifremiunuttumWidget4.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/woxisapp/generatedifreyenilemewidget/generated/GeneratedInputTextWidget8.dart';
import 'package:flutterapp/woxisapp/generatedifreyenilemewidget/generated/GeneratedInputTextWidget10.dart';
import 'package:flutterapp/woxisapp/generatedifreyenilemewidget/generated/GeneratedPageHeaderWidget3.dart';
import 'package:flutterapp/woxisapp/generatedifreyenilemewidget/generated/GeneratedInputTextWidget9.dart';
import 'package:flutterapp/woxisapp/generatedifreyenilemewidget/generated/GeneratedButtonPrimaryWidget3.dart';
import 'package:flutterapp/woxisapp/generatedifreyenilemewidget/generated/GeneratedIOSStatusBarBlackWidget3.dart';
import 'package:flutterapp/woxisapp/generatedifreyenilemewidget/generated/GeneratedInputTextWidget7.dart';

/* Frame Şifre Yenileme
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedifreYenilemeWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 44.0,
                child: GeneratedIOSStatusBarBlackWidget3(),
              ),
              Positioned(
                left: 16.0,
                top: null,
                right: 16.0,
                bottom: 350.0,
                width: null,
                height: 51.0,
                child: GeneratedButtonPrimaryWidget3(),
              ),
              Positioned(
                left: null,
                top: null,
                right: null,
                bottom: 309.0,
                width: 127.0,
                height: 21.0,
                child: TransformHelper.translate(
                    x: 9.00,
                    y: 0.00,
                    z: 0,
                    child: GeneratedifremiunuttumWidget4()),
              ),
              Positioned(
                left: null,
                top: null,
                right: null,
                bottom: 0.0,
                width: 375.0,
                height: 291.0,
                child: GeneratedIOSKeyboardLightAlphabeticWidget3(),
              ),
              Positioned(
                left: 119.0,
                top: 45.0,
                right: null,
                bottom: null,
                width: 138.0,
                height: 41.0,
                child: GeneratedWOXIS_SIYAH1Widget3(),
              ),
              Positioned(
                left: 16.0,
                top: 115.0,
                right: 16.0,
                bottom: null,
                width: null,
                height: 36.0,
                child: GeneratedPageHeaderWidget3(),
              ),
              Positioned(
                left: 16.0,
                top: 167.0,
                right: 16.0,
                bottom: null,
                width: null,
                height: 50.0,
                child: GeneratedInputTextWidget7(),
              ),
              Positioned(
                left: 17.0,
                top: 258.0,
                right: 15.0,
                bottom: null,
                width: null,
                height: 50.0,
                child: GeneratedInputTextWidget8(),
              ),
              Positioned(
                left: 17.0,
                top: 324.0,
                right: 15.0,
                bottom: null,
                width: null,
                height: 50.0,
                child: GeneratedInputTextWidget9(),
              ),
              Positioned(
                left: 16.0,
                top: 233.0,
                right: 16.0,
                bottom: null,
                width: null,
                height: 50.0,
                child: GeneratedInputTextWidget10(),
              )
            ]),
      ),
    ));
  }
}
