import 'package:flutter/material.dart';
import 'package:flutterapp/woxisapp/generatedantrenmandetaylar3widget/generated/GeneratedTextWidget3.dart';
import 'package:flutterapp/woxisapp/generatedantrenmandetaylar3widget/generated/GeneratedGroup13Widget2.dart';
import 'package:flutterapp/woxisapp/generatedantrenmandetaylar3widget/generated/GeneratedalmaArlWidget2.dart';
import 'package:flutterapp/woxisapp/generatedantrenmandetaylar3widget/generated/GeneratedGroup15Widget.dart';
import 'package:flutterapp/woxisapp/generatedantrenmandetaylar3widget/generated/GeneratedWOXIS_SIYAH1Widget6.dart';
import 'package:flutterapp/woxisapp/generatedantrenmandetaylar3widget/generated/GeneratedVector3Widget3.dart';
import 'package:flutterapp/woxisapp/generatedantrenmandetaylar3widget/generated/GeneratedIOSStatusBarBlackWidget7.dart';
import 'package:flutterapp/woxisapp/generatedantrenmandetaylar3widget/generated/GeneratedVector1Widget3.dart';
import 'package:flutterapp/woxisapp/generatedantrenmandetaylar3widget/generated/GeneratedTekrarSaysWidget2.dart';
import 'package:flutterapp/woxisapp/generatedantrenmandetaylar3widget/generated/Generated30KgWidget.dart';
import 'package:flutterapp/woxisapp/generatedantrenmandetaylar3widget/generated/GeneratedPageHeaderWidget7.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/woxisapp/generatedantrenmandetaylar3widget/generated/Generated8Widget2.dart';
import 'package:flutterapp/woxisapp/generatedantrenmandetaylar3widget/generated/GeneratedSpotterWidget2.dart';
import 'package:flutterapp/woxisapp/generatedantrenmandetaylar3widget/generated/GeneratedButtonPrimaryWidget8.dart';
import 'package:flutterapp/woxisapp/generatedantrenmandetaylar3widget/generated/Generated9Widget.dart';
import 'package:flutterapp/woxisapp/generatedantrenmandetaylar3widget/generated/GeneratedVector2Widget3.dart';
import 'package:flutterapp/woxisapp/generatedantrenmandetaylar3widget/generated/GeneratedGroup16Widget.dart';

/* Frame Antrenman Detayları 3
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAntrenmanDetaylar3Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 44.0,
                child: GeneratedIOSStatusBarBlackWidget7(),
              ),
              Positioned(
                left: 16.0,
                top: 136.0,
                right: 16.0,
                bottom: null,
                width: null,
                height: 36.0,
                child: GeneratedPageHeaderWidget7(),
              ),
              Positioned(
                left: null,
                top: null,
                right: null,
                bottom: 579.0,
                width: 123.0,
                height: 21.0,
                child: TransformHelper.translate(
                    x: -108.00,
                    y: 0.00,
                    z: 0,
                    child: GeneratedalmaArlWidget2()),
              ),
              Positioned(
                left: 18.0,
                top: 270.0,
                right: null,
                bottom: null,
                width: 317.5035400390625,
                height: 0.0,
                child: GeneratedVector1Widget3(),
              ),
              Positioned(
                left: 18.0,
                top: 246.0,
                right: null,
                bottom: null,
                width: 48.0,
                height: 21.0,
                child: Generated30KgWidget(),
              ),
              Positioned(
                left: null,
                top: null,
                right: null,
                bottom: 243.0,
                width: 2.0,
                height: 21.0,
                child: TransformHelper.translate(
                    x: -168.50, y: 0.00, z: 0, child: GeneratedTextWidget3()),
              ),
              Positioned(
                left: null,
                top: null,
                right: null,
                bottom: 499.0,
                width: 102.0,
                height: 21.0,
                child: TransformHelper.translate(
                    x: -118.50,
                    y: 0.00,
                    z: 0,
                    child: GeneratedTekrarSaysWidget2()),
              ),
              Positioned(
                left: 18.0,
                top: 350.0,
                right: null,
                bottom: null,
                width: 317.5035400390625,
                height: 0.0,
                child: GeneratedVector2Widget3(),
              ),
              Positioned(
                left: 18.0,
                top: 326.0,
                right: null,
                bottom: null,
                width: 16.0,
                height: 24.0,
                child: Generated9Widget(),
              ),
              Positioned(
                left: null,
                top: null,
                right: null,
                bottom: 410.0,
                width: 64.0,
                height: 24.0,
                child: TransformHelper.translate(
                    x: -137.50,
                    y: 0.00,
                    z: 0,
                    child: GeneratedSpotterWidget2()),
              ),
              Positioned(
                left: 20.0,
                top: 448.0,
                right: null,
                bottom: null,
                width: 318.0,
                height: 0.0,
                child: GeneratedVector3Widget3(),
              ),
              Positioned(
                left: 18.0,
                top: 412.0,
                right: null,
                bottom: null,
                width: 29.0,
                height: 24.0,
                child: Generated8Widget2(),
              ),
              Positioned(
                left: 16.0,
                top: null,
                right: 16.0,
                bottom: 46.0,
                width: null,
                height: 51.0,
                child: GeneratedButtonPrimaryWidget8(),
              ),
              Positioned(
                left: 95.0,
                top: 439.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 17.0,
                child: GeneratedGroup13Widget2(),
              ),
              Positioned(
                left: 119.0,
                top: 45.0,
                right: null,
                bottom: null,
                width: 138.0,
                height: 41.0,
                child: GeneratedWOXIS_SIYAH1Widget6(),
              ),
              Positioned(
                left: 20.0,
                top: 488.0,
                right: null,
                bottom: null,
                width: 120.0,
                height: 40.0,
                child: GeneratedGroup15Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 543.0,
                right: null,
                bottom: null,
                width: 120.0,
                height: 40.0,
                child: GeneratedGroup16Widget(),
              )
            ]),
      ),
    ));
  }
}
