import 'package:flutter/material.dart';
import 'package:flutterapp/woxisapp/generatedkaytlantrenmanlarwidget1/generated/GeneratedIOSStatusBarBlackWidget14.dart';
import 'package:flutterapp/woxisapp/generatedkaytlantrenmanlarwidget1/generated/GeneratedKaytlantrenmanlarframeWidget.dart';
import 'package:flutterapp/woxisapp/generatedkaytlantrenmanlarwidget1/generated/GeneratedGroup3Widget.dart';
import 'package:flutterapp/woxisapp/generatedkaytlantrenmanlarwidget1/generated/GeneratedWOXIS_SIYAH1Widget11.dart';

/* Frame Kayıtlı Antrenmanlar
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedKaytlAntrenmanlarWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 375.0,
      height: 812.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            ClipRRect(
              borderRadius: BorderRadius.zero,
              child: Container(
                color: Color.fromARGB(255, 255, 255, 255),
              ),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: null,
              width: null,
              height: 44.0,
              child: GeneratedIOSStatusBarBlackWidget14(),
            ),
            Positioned(
              left: 115.0,
              top: 45.0,
              right: null,
              bottom: null,
              width: 138.0,
              height: 41.0,
              child: GeneratedWOXIS_SIYAH1Widget11(),
            ),
            Positioned(
              left: 14.0,
              top: 52.0,
              right: null,
              bottom: null,
              width: 17.731151580810547,
              height: 27.733333587646484,
              child: GeneratedGroup3Widget(),
            ),
            Positioned(
              left: 0.0,
              top: 99.0,
              right: null,
              bottom: null,
              width: 375.0,
              height: 668.0,
              child: GeneratedKaytlantrenmanlarframeWidget(),
            )
          ]),
    ));
  }
}
